In [ ]:
from __future__ import print_function
from __future__ import division
from __future__ import absolute_import

# 4.1 python 复习 

## Basic object

### variable

In [ ]:
x = 1
print(x)
print(type(x))

In [ ]:
y = '1'
print(y)
print(type(y))

In [ ]:
print(x + y)

In [ ]:
print(type(x + y))

In [ ]:
print(x + int(y))

### list

In [ ]:
x = [1,2,3,4,5]

In [ ]:
x[0] 

In [ ]:
x.append(6)
print(x)

In [ ]:
x.pop()

In [ ]:
x

### dictionary

In [ ]:
x = {"dog": 1, "cat": 2, "lion":3}

In [ ]:
x[0]

In [ ]:
x["dog"]

In [ ]:
x.keys()

In [ ]:
x.items()

### for loop

In [ ]:
x = [1,2,3,4,5]
for i in x:
    print(i)

In [ ]:
for i in x:
    print(i+1)

In [ ]:
for i in range(10):
    print(i)

### if else

In [ ]:
x = [1,2,3,4,5]

for i in x:
    if i%2 == 0:
        print(i)

In [ ]:
for i in x:
    if i%2 == 0:
        print("{} is odds".format(i))
    else:
        print("{} is ".format(i))

In [ ]:
for i in x:
    if i%2 == 0:
        print("{} is odds".format(i))
    elif i % 5 == 0:
        print("{} is 5".format(i))
    else:
        print("Others")

### enumerate 

In [1]:
x = [10,20,30,40,50]
for k, v in enumerate(x):
    print(k ,v)

0 10
1 20
2 30
3 40
4 50


In [2]:
y = [0]*5
for k, v in enumerate(x):
    y[k] = v
    
print(y)

[10, 20, 30, 40, 50]


In [ ]:
x is y

## Numpy basic

In [3]:
import numpy as np

In [4]:
x_array = np.array([1,2,3,4,5])

In [5]:
x_array + 1

array([2, 3, 4, 5, 6])

In [6]:
x_array * 2

array([ 2,  4,  6,  8, 10])

In [8]:
y_array = np.array([5])

In [9]:
x_array * y_array

array([ 5, 10, 15, 20, 25])

In [10]:
x_array + y_array

array([ 6,  7,  8,  9, 10])

In [11]:
x_array.sum()

15

In [12]:
percentage = x_array / x_array.sum()

In [13]:
print(percentage)

[0.06666667 0.13333333 0.2        0.26666667 0.33333333]
